# Generated by Django 5.0.14 on 2026-02-07 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_remove_banner_color_banner_action_link_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'ordering': ['order', '-created_at']},
        ),
        migrations.AddField(
            model_name='banner',
            name='target_id',
            field=models.CharField(blank=True, help_text='ID of product or category', max_length=100),
        ),
        migrations.AddField(
            model_name='banner',
            name='target_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('url', 'External URL'), ('none', 'None')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='banner',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='action_link',
            field=models.CharField(blank=True, help_text='External URL if target_type is url', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='bg_color',
            field=models.CharField(default='0xFF42A5F5', help_text='Hex color code e.g. 0xFFE040FB', max_length=10),
        ),
        migrations.AlterField(
            model_name='banner',
            name='button_text',
            field=models.CharField(blank=True, default='View Now', max_length=50),
        ),
    ]
