# Generated by Django 5.0.14 on 2026-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order_index', models.IntegerField(default=0, help_text='Order in which categories are displayed')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order_index', 'name'],
            },
        ),
    ]
