# Generated by Django 5.0.14 on 2026-02-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total',
            new_name='total_amount',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='price',
            new_name='price_at_purchase',
        ),
        migrations.AddField(
            model_name='order',
            name='phone_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
